/* Vaultline is intentionally self-contained: all rolls use the displayed data below. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const R={Common:['#a9b1c8',.54,1],Uncommon:['#65d894',.27,1.7],Rare:['#5aa8ff',.12,3.3],Epic:['#bd70ff',.052,8],Legendary:['#ffad4c',.015,25],Mythic:['#ff4fa1',.003,95]};
const cases=[
 {id:'field',name:'Field Signal',price:400,level:1,c1:'#426481',c2:'#141f37',pool:['Slate Relay','Moss Signal','Tidewire','Copper Grid']},
 {id:'nova',name:'Nova Cache',price:1800,level:3,c1:'#b552e8',c2:'#25164d',pool:['Ion Bloom','Night Runner','Violet Divide','Static Bloom']},
 {id:'ember',name:'Ember Protocol',price:7500,level:6,c1:'#ea7147',c2:'#48202a',pool:['Furnace','Solar Flare','Ash Circuit','Redline Echo']},
 {id:'abyss',name:'Abyss Archive',price:30000,level:10,c1:'#2ad6c4',c2:'#12384b',pool:['Abyssal Fold','Deep Vector','Glass Current','Azure Static']},
 {id:'crown',name:'Crown Reserve',price:125000,level:15,c1:'#e2ad55',c2:'#47331d',pool:['Gilded Sector','Royal Fault','Aurum Pulse','Sun Cipher']},
 {id:'void',name:'Void Reliquary',price:600000,level:22,c1:'#d950b6',c2:'#24122f',pool:['Void Choir','Magenta Rift','Spectral Debt','Black Halo']}
];
const weapons=['Kestrel Carbine','Morrow-9','Helix Sidearm','Bastion Scatter','Vega SMG','Orchid DMR','Rook LMG','Talon Blade'];
const upgrades=[
 {id:'click',name:'Contract Pay',desc:'More cash for every contract run.',base:150,unlock:1,effect:l=>`$${12+l*9} per click`},
 {id:'idle',name:'Remote Rigs',desc:'Deploy autonomous salvage rigs.',base:420,unlock:2,effect:l=>`$${l*3} per second`},
 {id:'xp',name:'Intel Pipeline',desc:'Earn more operator XP per action.',base:1100,unlock:4,effect:l=>`${100+l*15}% XP gain`},
 {id:'discount',name:'Broker Network',desc:'Reduce all sealed case prices.',base:3800,unlock:7,effect:l=>`${l*3}% case discount`},
 {id:'market',name:'Sharp Eye',desc:'Receive more when liquidating vault items.',base:9000,unlock:10,effect:l=>`${l*4}% sell bonus`}
];
const missions=[
 {id:'runs',name:'First shift',desc:'Run 15 contracts.',key:'clicks',goal:15,cash:250,xp:70},
 {id:'opens',name:'Crack the seal',desc:'Open 3 cases.',key:'opens',goal:3,cash:650,xp:140},
 {id:'sale',name:'Clear stock',desc:'Sell 2 vault items.',key:'sold',goal:2,cash:850,xp:160},
 {id:'rare',name:'Blue signal',desc:'Find a Rare item or better.',key:'rare',goal:1,cash:1000,xp:200}
];
const achievements=[
 {id:'first',name:'First Signal',desc:'Open your first case.',test:s=>s.stats.opens>=1}, {id:'seller',name:'Quartermaster',desc:'Sell your first item.',test:s=>s.stats.sold>=1}, {id:'rare',name:'Bright Find',desc:'Pull an Epic item.',test:s=>s.stats.epic>=1}, {id:'vault',name:'Vault Keeper',desc:'Own 10 items.',test:s=>s.inventory.length>=10}, {id:'cash',name:'Six Figures',desc:'Reach $100,000.',test:s=>s.cash>=100000}, {id:'legend',name:'Golden Hour',desc:'Pull a Legendary item.',test:s=>s.stats.legendary>=1}, {id:'collector',name:'Deep Collection',desc:'Own 30 items.',test:s=>s.inventory.length>=30}, {id:'million',name:'One Million',desc:'Reach $1,000,000.',test:s=>s.cash>=1000000}
];
const fresh=()=>({cash:250,xp:0,level:1,inventory:[],up:{click:0,idle:0,xp:0,discount:0,market:0},stats:{earned:250,spent:0,opens:0,obtained:0,sold:0,clicks:0,rare:0,epic:0,legendary:0,mythic:0,best:0,play:0},claimed:{},achieved:{},daily:'',streak:0,sound:true,marketSeed:Math.random()});
let state;try{state=Object.assign(fresh(),JSON.parse(localStorage.vaultline||'{}'));state.up=Object.assign(fresh().up,state.up);state.stats=Object.assign(fresh().stats,state.stats)}catch{state=fresh()}let current='home',rolling=false,started=Date.now();
const fmt=n=>'$'+Math.floor(n).toLocaleString();const rank=()=>state.level>=22?'TITAN':state.level>=15?'LEGEND':state.level>=10?'MASTER':state.level>=6?'ELITE':state.level>=3?'SPECIALIST':'RECRUIT';
function save(){state.stats.play+=Math.floor((Date.now()-started)/1000);started=Date.now();localStorage.vaultline=JSON.stringify(state)}
function clickPay(){return (12+state.up.click*9)*(1+Math.floor(state.level/15)*.1)}function idlePay(){return state.up.idle*3}function xpNeed(){return 100+state.level*65}function gainXP(n){n*=1+state.up.xp*.15;state.xp+=n;while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;toast(`LEVEL ${state.level} // ${rank()} unlocked`);sound(620,.18)}check()}
function value(item){let multiplier=R[item.rarity][2]*(1+(1-item.float)*.26)*(item.seed%19===0?1.35:1);let mood=1+Math.sin(state.marketSeed+item.seed)*.09;if(item.rarity==='Epic'||item.rarity==='Legendary'||item.rarity==='Mythic')mood*=1.18;return Math.round(item.base*multiplier*mood)}
function condition(f){return f<.07?'Factory Fresh':f<.18?'Minimal Wear':f<.4?'Field Tested':f<.7?'Well Worn':'Battle Scarred'}
function rollRarity(){let r=Math.random(),sum=0;for(const [name,x] of Object.entries(R)){sum+=x[1];if(r<sum)return name}return 'Common'}
function itemFrom(c,force){let rarity=force||rollRarity(),float=Math.random(),seed=Math.floor(Math.random()*1000);let special=rarity==='Mythic'&&Math.random()<.33;return {id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),weapon:special?'Aether Fang':weapons[Math.floor(Math.random()*(weapons.length-(rarity==='Mythic'?0:1)))],skin:special?'Singularity Edge':c.pool[Math.floor(Math.random()*c.pool.length)],rarity,float,seed,base:c.price*.72,case:c.id,fav:false,at:Date.now()}}
function art(item){let color=R[item.rarity][0];let hue=(item.seed*37)%360;return `<div class="weapon-art" style="--skin:linear-gradient(130deg,${color},hsl(${hue} 85% 58%))"></div>`}
function renderHeader(){let vault=state.inventory.reduce((a,i)=>a+value(i),0);$('#cash').textContent=fmt(state.cash);$('#vault').textContent=fmt(vault);$('#level').textContent=state.level;$('#xp').textContent=`${Math.floor(state.xp)} / ${xpNeed()} XP`;$('#xpBar').style.width=`${state.xp/xpNeed()*100}%`;$('#invCount').textContent=state.inventory.length;$('#clickValue').textContent=fmt(clickPay());$('#passiveValue').textContent=fmt(idlePay())+'/s';$('#rankName').textContent=rank();$('#rankDots').innerHTML=Array.from({length:7},(_,i)=>`<i class="${i<Math.ceil(state.level/4)?'on':''}"></i>`).join('');$('#dailyText').textContent=canDaily()?'READY':'CLAIMED'}
function renderCases(){let discount=1-state.up.discount*.03;$('#caseGrid').innerHTML=cases.map(c=>`<article class="case-card ${state.level<c.level?'locked':''}" data-case="${c.id}" style="--case1:${c.c1};--case2:${c.c2}"><div class="case-visual"><div class="mini-case">VL<br><small>${c.name.split(' ')[0]}</small></div></div><h3>${c.name}</h3><p>${state.level<c.level?`UNLOCKS AT LEVEL ${c.level}`:'SEALED ITEM POOL'}</p><div class="case-price"><b>${fmt(c.price*discount)}</b><span>INSPECT →</span></div></article>`).join('');$$('[data-case]').forEach(x=>x.onclick=()=>inspectCase(cases.find(c=>c.id===x.dataset.case)))}
function renderInventory(){let q=$('#search').value.toLowerCase(),filter=$('#rarityFilter').value,sort=$('#sort').value;let arr=state.inventory.filter(i=>(filter==='all'||i.rarity===filter)&&`${i.weapon} ${i.skin}`.toLowerCase().includes(q));arr.sort((a,b)=>sort==='value'?value(b)-value(a):sort==='float'?a.float-b.float:b.at-a.at);$('#inventoryGrid').innerHTML=arr.map(card).join('');$('#emptyInventory').style.display=state.inventory.length?'none':'block';$$('.item-card').forEach(x=>x.onclick=()=>inspectItem(state.inventory.find(i=>i.id===x.dataset.item)))}
function card(i){let c=R[i.rarity][0];return `<article class="item-card" data-item="${i.id}" style="--rarity:${c}">${art(i)}<div class="item-info"><b>${i.weapon} · ${i.skin}</b><span>${i.rarity.toUpperCase()} · ${condition(i.float)}</span><footer><span>FLT ${i.float.toFixed(3)}</span><strong>${fmt(value(i))}</strong></footer></div></article>`}
function renderUpgrades(){$('#upgradeGrid').innerHTML=upgrades.map(u=>{let l=state.up[u.id],cost=Math.floor(u.base*Math.pow(1.7,l)),locked=state.level<u.unlock;return `<article class="upgrade"><p class="eyebrow">LEVEL ${l} ${locked?'// LOCKED':''}</p><h3>${u.name}</h3><p>${u.desc}</p><footer><span>${u.effect(l)} → <b>${u.effect(l+1)}</b></span><button class="buy-btn" data-up="${u.id}" ${locked||state.cash<cost?'disabled':''}>${fmt(cost)}</button></footer></article>`}).join('');$$('[data-up]').forEach(b=>b.onclick=()=>buyUpgrade(b.dataset.up))}
function renderMissions(){$('#missionGrid').innerHTML=missions.map(m=>{let n=Math.min(state.stats[m.key]||0,m.goal),done=n>=m.goal,claim=state.claimed[m.id];return `<article class="mission"><p class="eyebrow">${claim?'COMPLETE':'REWARD '+fmt(m.cash)}</p><h3>${m.name}</h3><p>${m.desc}</p><div class="progress"><i style="width:${n/m.goal*100}%"></i></div><footer><span>${n} / ${m.goal}</span><button class="claim-btn" data-mission="${m.id}" ${!done||claim?'disabled':''}>${claim?'CLAIMED':`CLAIM +${m.xp} XP`}</button></footer></article>`}).join('');$$('[data-mission]').forEach(b=>b.onclick=()=>claimMission(b.dataset.mission))}
function renderAchievements(){let count=achievements.filter(a=>state.achieved[a.id]).length;$('#achievementCount').textContent=`${count} / ${achievements.length} unlocked`;$('#achievementGrid').innerHTML=achievements.map(a=>`<article class="achievement ${state.achieved[a.id]?'unlocked':''}"><span class="badge">${state.achieved[a.id]?'★':'◇'}</span><h3>${a.name}</h3><p>${a.desc}</p></article>`).join('')}
function renderMarket(){let listings=cases.flatMap(c=>c.pool.slice(0,2).map((skin,n)=>({weapon:weapons[(n+c.level)%weapons.length],skin,rarity:['Uncommon','Rare','Epic','Legendary'][Math.min(3,Math.floor(c.level/5))],float:.08+n*.18,seed:c.level*73+n,base:c.price*.72,case:c.id}))).slice(0,10);$('#marketEvent').innerHTML=`<b>◈ COLLECTOR DEMAND</b><br><small>High-grade finishes currently carry an 18% local premium.</small>`;$('#marketGrid').innerHTML=listings.map(i=>`<article class="market-card" style="--rarity:${R[i.rarity][0]}">${art(i)}<div><b>${i.weapon}</b><small>${i.skin} · ${i.rarity}</small></div><footer><strong>${fmt(value(i))}</strong><br><button class="buy-btn" data-market='${encodeURIComponent(JSON.stringify(i))}' ${state.cash<value(i)?'disabled':''}>ACQUIRE</button></footer></article>`).join('');$$('[data-market]').forEach(b=>b.onclick=()=>buyMarket(JSON.parse(decodeURIComponent(b.dataset.market))))}
function renderStats(){let st=state.stats;let data=[['TOTAL EARNED',fmt(st.earned)],['CASES OPENED',st.opens],['ITEMS FOUND',st.obtained],['ITEMS SOLD',st.sold],['CONTRACT RUNS',st.clicks],['BEST PULL',fmt(st.best)],['RARE+ FINDS',st.rare],['PLAY TIME',Math.floor(st.play/60)+'m']];$('#statsGrid').innerHTML=data.map(x=>`<article class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');$('#chartBars').innerHTML=Array.from({length:14},(_,i)=>`<i style="height:${20+(Math.sin(i*4+state.marketSeed)*.5+.5)*80}%"></i>`).join('')}
function render(){renderHeader();renderCases();renderInventory();renderUpgrades();renderMissions();renderAchievements();renderMarket();renderStats();save()}
function inspectCase(c){let discount=1-state.up.discount*.03;let odds=Object.entries(R).map(([n,d])=>`<span style="--rarity:${d[0]}">${n} <b>${(d[1]*100).toFixed(1)}%</b></span>`).join('');show(`<div class="modal-head"><div><p class="eyebrow">SEALED DROP // FAIR ODDS</p><h2>${c.name}</h2></div><button class="close">×</button></div><p>Every opening uses the exact independent distribution below. No pity timers or altered chances.</p><div class="odds">${odds}</div><p>Estimated item pool value: ${fmt(c.price*.8)} · Unlock level ${c.level}</p><button class="open-btn" data-open="${c.id}" ${state.cash<c.price*discount||state.level<c.level?'disabled':''}>OPEN FOR ${fmt(c.price*discount)}</button>`);$('.close').onclick=hide;let b=$('[data-open]');if(b)b.onclick=()=>openCase(c)}
function openCase(c){if(rolling)return;let cost=Math.floor(c.price*(1-state.up.discount*.03));if(state.cash<cost)return;rolling=true;state.cash-=cost;state.stats.spent+=cost;let final=itemFrom(c),samples=Array.from({length:19},()=>itemFrom(c));samples.splice(15,0,final);show(`<div class="modal-head"><div><p class="eyebrow">DECRYPTING // ${c.name.toUpperCase()}</p><h2>Signal incoming…</h2></div></div><div class="roll"><div class="roll-track">${samples.map(i=>`<div class="roll-card" style="--rarity:${R[i.rarity][0]}">${i.weapon}<br><b>${i.skin}</b></div>`).join('')}</div></div><p class="eyebrow" style="text-align:center">VERIFYING ROLL…</p>`);setTimeout(()=>$('.roll-track').style.transform='translateX(-1660px)',40);sound(180,.12);setTimeout(()=>reveal(final),3200)}
function reveal(i){state.inventory.unshift(i);state.stats.opens++;state.stats.obtained++;state.stats.best=Math.max(state.stats.best,value(i));if(['Rare','Epic','Legendary','Mythic'].includes(i.rarity))state.stats.rare++;if(i.rarity==='Epic')state.stats.epic++;if(i.rarity==='Legendary')state.stats.legendary++;if(i.rarity==='Mythic')state.stats.mythic++;gainXP(28);check();let rare=['Legendary','Mythic'].includes(i.rarity);show(`<div class="reveal ${rare?'rare-reveal':''}" style="--rarity:${R[i.rarity][0]}"><p class="eyebrow">${rare?'EXCEPTIONAL SIGNAL':'ITEM SECURED'}</p>${art(i)}<p style="color:${R[i.rarity][0]}">${i.rarity.toUpperCase()} · ${condition(i.float)}</p><h1>${i.weapon}<br><i>${i.skin}</i></h1><div class="value">${fmt(value(i))}</div><p>FLOAT ${i.float.toFixed(3)} · PATTERN #${i.seed}</p><button class="open-btn close">ADD TO VAULT</button></div>`);sound(rare?720:430,.25);$('.close').onclick=()=>{hide();rolling=false;render()}}
function inspectItem(i){show(`<div class="modal-head"><div><p class="eyebrow">VAULT ITEM // ${i.id.toUpperCase()}</p><h2>${i.weapon} · ${i.skin}</h2></div><button class="close">×</button></div>${art(i)}<div class="odds"><span style="--rarity:${R[i.rarity][0]}">RARITY <b>${i.rarity}</b></span><span style="--rarity:${R[i.rarity][0]}">CONDITION <b>${condition(i.float)}</b></span><span style="--rarity:${R[i.rarity][0]}">FLOAT <b>${i.float.toFixed(4)}</b></span><span style="--rarity:${R[i.rarity][0]}">PATTERN <b>#${i.seed}</b></span></div><p>Local market estimate <b style="color:var(--mint)">${fmt(value(i))}</b>. Factory condition and select pattern seeds command a premium.</p><button class="open-btn" data-sell="${i.id}">SELL ITEM · ${fmt(Math.floor(value(i)*(1+state.up.market*.04)))}</button>`);$('.close').onclick=hide;$('[data-sell]').onclick=()=>sell(i)}
function sell(i){let sale=Math.floor(value(i)*(1+state.up.market*.04));state.cash+=sale;state.stats.earned+=sale;state.stats.sold++;state.inventory=state.inventory.filter(x=>x.id!==i.id);hide();toast(`ITEM SOLD // +${fmt(sale)}`);sound(520,.12);check();render()}
function buyMarket(i){let price=value(i);if(state.cash<price)return;state.cash-=price;state.stats.spent+=price;state.inventory.unshift({...i,id:Date.now().toString(36),fav:false,at:Date.now()});toast('MARKET ACQUISITION SECURED');render()}
function buyUpgrade(id){let u=upgrades.find(x=>x.id===id),cost=Math.floor(u.base*Math.pow(1.7,state.up[id]));if(state.cash<cost)return;state.cash-=cost;state.stats.spent+=cost;state.up[id]++;toast(`${u.name.toUpperCase()} IMPROVED`);sound(600,.1);render()}
function claimMission(id){let m=missions.find(x=>x.id===id);state.claimed[id]=true;state.cash+=m.cash;state.stats.earned+=m.cash;gainXP(m.xp);toast(`CONTRACT COMPLETE // +${fmt(m.cash)}`);render()}
function check(){achievements.forEach(a=>{if(!state.achieved[a.id]&&a.test(state)){state.achieved[a.id]=true;toast(`ACHIEVEMENT // ${a.name}`)}})}
function canDaily(){return state.daily!==new Date().toDateString()}function claimDaily(){if(!canDaily())return;state.daily=new Date().toDateString();state.streak=(state.streak%7)+1;let cash=100*state.streak*state.level;state.cash+=cash;state.stats.earned+=cash;gainXP(30*state.streak);toast(`DAILY DROP // ${fmt(cash)} + XP`);render()}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.classList.remove('show'),2700)}
function sound(f,d){if(!state.sound)return;try{let c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}catch{}}
function show(html){$('#modalBox').innerHTML=html;$('#modal').classList.add('show')}function hide(){$('#modal').classList.remove('show')}function nav(p){current=p;$$('.page').forEach(x=>x.classList.toggle('active',x.id===p+'Page'));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#crumb').innerHTML=`COMMAND CENTER <em>/ ${p.toUpperCase()}</em>`;$('.side').classList.remove('open');render()}
$('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(b)nav(b.dataset.page)};$$('[data-page]').forEach(b=>b.onclick=()=>nav(b.dataset.page));$('#menu').onclick=()=>$('.side').classList.toggle('open');$('#daily').onclick=claimDaily;$('#sound').onclick=()=>{state.sound=!state.sound;$('#sound').textContent=state.sound?'♬':'♩̸';save()};$('#work').onclick=e=>{let n=clickPay();state.cash+=n;state.stats.earned+=n;state.stats.clicks++;gainXP(5);let f=document.createElement('b');f.className='float';f.textContent='+'+fmt(n);f.style.left=e.clientX+'px';f.style.top=e.clientY+'px';document.body.append(f);setTimeout(()=>f.remove(),1000);sound(330,.06);check();renderHeader();if(current==='home')renderMissions()};$('#search').oninput=renderInventory;$('#rarityFilter').onchange=renderInventory;$('#sort').onchange=renderInventory;Object.keys(R).forEach(r=>$('#rarityFilter').insertAdjacentHTML('beforeend',`<option value="${r}">${r}</option>`));
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state)],{type:'application/json'}));a.download='vaultline-save.json';a.click()};$('#importInput').onchange=e=>{let r=new FileReader();r.onload=()=>{try{state=Object.assign(fresh(),JSON.parse(r.result));render();toast('SAVE IMPORTED')}catch{toast('INVALID SAVE FILE')}};r.readAsText(e.target.files[0])};$('#resetBtn').onclick=()=>{if(confirm('Reset your entire local Vaultline save?')){state=fresh();render();nav('home')}};
setInterval(()=>{let n=idlePay();if(n){state.cash+=n;state.stats.earned+=n;renderHeader()}state.marketSeed+=.02;save()},1000);setInterval(()=>{if(current==='market')renderMarket()},15000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
